### ISSUE TITLE
Low accuracy for diffusion policy+aloha env+sim_transfer_cude_human dataset

### ISSUE THREAD

**Issue by Kimho666** [huggingface/lerobot#502]
I'm trying to use diffusion model and aloha env to train on sim_transfer_cude_human dataset. But after 60000 training step, the evaluation accuracy is only 2%-6%. Idont know why? If I load pre-trained act policy, the accuracy can reach 80%.

**Comment by Kimho666** [comment]
# @package _global_

# Defaults for training for the PushT dataset as per https://github.com/real-stanford/diffusion_policy.
# Note: We do not track EMA model weights as we discovered it does not improve the results. See
#       https://github.com/huggingface/lerobot/pull/134 for more details.

seed: 100000
dataset_repo_id: lerobot/aloha_sim_transfer_cube_human

override_dataset_stats:
  # TODO(rcadene, alexander-soare): should we remove image stats as well? do we use a pretrained vision model?
  observation.images.top:
    mean: [[[0.5]], [[0.5]], [[0.5]]]  # (c,1,1)
    std: [[[0.5]], [[0.5]], [[0.5]]]  # (c,1,1)
  # TODO(rcadene, alexander-soare): we override state and action stats to use the same as the pretrained model
  # from the original codebase, but we should remove these and train our own pretrained model
  # observation.state:
  #   min: [13.456424, 32.938293]
  #   max: [496.14618, 510.9579]
  # action:
  #   min: [12.0, 25.0]
  #   max: [511.0, 511.0]

training:
  offline_steps: 200000
  online_steps: 0
  eval_freq: 25000
  save_freq: 25000
  save_checkpoint: true

  batch_size: 64
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  delta_timestamps:
    observation.images.top: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1 - ${policy.n_obs_steps} + ${policy.horizon})]"

  # The original implementation doesn't sample frames for the last 7 steps,
  # which avoids excessive padding and leads to improved training results.
  drop_n_last_frames: 7  # ${policy.horizon} - ${policy.n_action_steps} - ${policy.n_obs_steps} + 1

eval:
  n_episodes: 50
  batch_size: 50

policy:
  name: diffusion

  # Input / output structure.
  n_obs_steps: 2
  horizon: 16
  n_action_steps: 8

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.images.top: [3, 480, 640]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.images.top: mean_std
    observation.state: min_max
  output_normalization_modes:
    action: min_max

  # Architecture / modeling.
  # Vision backbone.
  vision_backbone: resnet18
  crop_shape: [84, 84]
  crop_is_random: True
  pretrained_backbone_weights: null
  use_group_norm: True
  spatial_softmax_num_keypoints: 32
  # Unet.
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  diffusion_step_embed_dim: 128
  use_film_scale_modulation: True
  # Noise scheduler.
  noise_scheduler_type: DDPM
  num_train_timesteps: 100
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon # epsilon / sample
  clip_sample: True
  clip_sample_range: 1.0

  # Inference
  num_inference_steps: null  # if not provided, defaults to `num_train_timesteps`

  # Loss computation
  do_mask_loss_for_padding: false

**Comment by Kimho666** [comment]
This is my policy config. 
[diffusion4aloha.txt](https://github.com/user-attachments/files/17671776/diffusion4aloha.txt)

**Comment by Kimho666** [comment]
![image](https://github.com/user-attachments/assets/427b4288-499f-41e3-ab12-766348e48700)

**Comment by CallMeFrozenBanana** [comment]
I adapted the codes to train diffusion policy on the aloha_sim_transfer_cube_scripted dataset and get the same results as you.
The EE always tries to clip a wrong position.
Just like below:
![image](https://github.com/user-attachments/assets/d06553ea-9a15-42a3-8df9-45b2db05b64a)

**Comment by CallMeFrozenBanana** [comment]
> ![image](https://private-user-images.githubusercontent.com/137678908/384203965-427b4288-499f-41e3-ab12-766348e48700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDE0MjMsIm5iZiI6MTczMzMwMTEyMywicGF0aCI6Ii8xMzc2Nzg5MDgvMzg0MjAzOTY1LTQyN2I0Mjg4LTQ5OWYtNDFlMy1hYjEyLTc2NjM0OGU0ODcwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwODMyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzVkNGEyOWU4Y2ZiMDQxYWExNmUyOWM2OTAyYmQwZTkxZTY2YTZiZWUyMWQwM2U1YTdkNGU3ODdhY2ViZGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OYgflE9gZ7qIf5nPqNXu9Lxt1ktks0_fbjrqO1h5Rzc)

I find that set a larger chunk size can slightly increase the success rate:
<img width="760" alt="image" src="https://github.com/user-attachments/assets/1baecc6e-dd17-4d5a-b481-944289721bb5">

**Comment by CallMeFrozenBanana** [comment]
The crop_shape you used is : [84, 84] which isn't appropriate to the 480 x 640 inputs. I have tried it but nothing works. Now I suspect that the problem is caused by the SpatialSoftmax layer.

**Comment by CallMeFrozenBanana** [comment]
> The crop_shape you used is : [84, 84] which isn't appropriate to the 480 x 640 inputs. I have tried it but nothing works. Now I suspect that the problem is caused by the SpatialSoftmax layer.

Besides, change the cropping method to centered cropping, and you will find that everything works properly.
![image](https://github.com/user-attachments/assets/92ff39c5-75b6-4a4d-937f-e6a879f7b177)

**Comment by linCC111** [comment]
@CallMeFrozenBanana What is the configuration of your diffusion policy?

**Comment by Taylor-Liu** [comment]
> > The crop_shape you used is : [84, 84] which isn't appropriate to the 480 x 640 inputs. I have tried it but nothing works. Now I suspect that the problem is caused by the SpatialSoftmax layer.
> 
> Besides, change the cropping method to centered cropping, and you will find that everything works properly. ![image](https://private-user-images.githubusercontent.com/26683954/393176602-92ff39c5-75b6-4a4d-937f-e6a879f7b177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTgzMTMsIm5iZiI6MTczMzY1ODAxMywicGF0aCI6Ii8yNjY4Mzk1NC8zOTMxNzY2MDItOTJmZjM5YzUtNzViNi00YTRkLTkzN2YtZTZhODc5ZjdiMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDExNDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOGU4ZmE5NGEwODhjMmZmOGFmM2MyMzQwMjYyMjQ2NmYwZmVjOTRjOWVlNjk2ZTNhYWQ1MmQ5MjAxN2FjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea0h0d80L1ymnTZE0apmsQoLzvO2hK-8OVhwZtCukl4)

Hi, what's your policy config and possible code modifications for this result?

**Comment by CallMeFrozenBanana** [comment]
> > > The crop_shape you used is : [84, 84] which isn't appropriate to the 480 x 640 inputs. I have tried it but nothing works. Now I suspect that the problem is caused by the SpatialSoftmax layer.
> > 
> > 
> > Besides, change the cropping method to centered cropping, and you will find that everything works properly. ![image](https://private-user-images.githubusercontent.com/26683954/393176602-92ff39c5-75b6-4a4d-937f-e6a879f7b177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTgzMTMsIm5iZiI6MTczMzY1ODAxMywicGF0aCI6Ii8yNjY4Mzk1NC8zOTMxNzY2MDItOTJmZjM5YzUtNzViNi00YTRkLTkzN2YtZTZhODc5ZjdiMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDExNDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOGU4ZmE5NGEwODhjMmZmOGFmM2MyMzQwMjYyMjQ2NmYwZmVjOTRjOWVlNjk2ZTNhYWQ1MmQ5MjAxN2FjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea0h0d80L1ymnTZE0apmsQoLzvO2hK-8OVhwZtCukl4)
> 
> Hi, what's your policy config and possible code modifications for this result?

Hi, you only need to change these two configs as follows:
  crop_shape: [440, 560]
  crop_is_random: False

Here is my config file ⬇️
```
# @package _global_

# Defaults for training for the PushT dataset as per https://github.com/real-stanford/diffusion_policy.
# Note: We do not track EMA model weights as we discovered it does not improve the results. See
#       https://github.com/huggingface/lerobot/pull/134 for more details.

seed: 100000
dataset_repo_id: lerobot/aloha_sim_transfer_cube_scripted
root: /data/dataset/HuggingFace-Download-Accelerator/hf_hub
 
override_dataset_stats:
  # TODO(rcadene, alexander-soare): should we remove image stats as well? do we use a pretrained vision model?
  observation.images.top:
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  # TODO(rcadene, alexander-soare): we override state and action stats to use the same as the pretrained model
  # from the original codebase, but we should remove these and train our own pretrained model
  # observation.state:
  #   min: [13.456424, 32.938293]
  #   max: [496.14618, 510.9579]
  # action:
  #   min: [12.0, 25.0]
  #   max: [511.0, 511.0]

training:
  offline_steps: 200000
  online_steps: 0
  eval_freq: 20000
  save_freq: 20000
  save_checkpoint: true

  batch_size: 20
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  delta_timestamps:
    observation.images.top: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1 - ${policy.n_obs_steps} + ${policy.horizon})]"

  # The original implementation doesn't sample frames for the last 7 steps,
  # which avoids excessive padding and leads to improved training results.
  drop_n_last_frames: 7  # ${policy.horizon} - ${policy.n_action_steps} - ${policy.n_obs_steps} + 1

eval:
  n_episodes: 25
  batch_size: 25

policy:
  name: diffusion

  # Input / output structure.
  n_obs_steps: 2
  horizon: 16
  n_action_steps: 8

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.images.top: [3, 480, 640]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.images.top: mean_std 
    observation.state: min_max
  output_normalization_modes:
    action: min_max

  # Architecture / modeling.
  # Vision backbone.
  vision_backbone: resnet18
  crop_shape: [440, 560]
  crop_is_random: False
  pretrained_backbone_weights: null
  use_group_norm: True
  spatial_softmax_num_keypoints: 32
  # Unet.
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  diffusion_step_embed_dim: 128 
  use_film_scale_modulation: True
  # Noise scheduler.
  noise_scheduler_type: DDPM
  num_train_timesteps: 100
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon # epsilon / sample
  clip_sample: True
  clip_sample_range: 1.0
 
  # Inference
  num_inference_steps: null  # if not provided, defaults to `num_train_timesteps`

  # Loss computation
  do_mask_loss_for_padding: false
  use_l1_loss: False
```

**Comment by Kimho666** [comment]
OK, thank u ! I am trying it.

**Comment by Kimho666** [comment]
![image](https://github.com/user-attachments/assets/eaeedf7b-e169-4ffb-bd0e-c2130a7772cd)
![image](https://github.com/user-attachments/assets/be2ab933-3aae-4144-a72e-dd68f2db966a)

I have modifiied the 'crop size' and 'random crop', but the success rate is also 4% (after 70000 steps). @CallMeFrozenBanana

**Comment by Kimho666** [comment]
![image](https://github.com/user-attachments/assets/b52e3d36-637a-480d-9fcb-9a71e6953bae)
After using @CallMeFrozenBanana ‘s yaml, it always pick cude from the position as shown in the picture above. But the real cube is random.

**Comment by Sui0206** [comment]
@Kimho666 Hello,
I have noticed that your 'num_train_timesteps' is only 10, i think this caused the bad performance of your policy, and I think you can just turn it to 100 to achieve a good result.

**Comment by CallMeFrozenBanana** [comment]
@Kimho666 Sorry that I missed the message for so long. Have you solved this problem?

**Comment by Kimho666** [comment]
> [@Kimho666](https://github.com/Kimho666) Sorry that I missed the message for so long. Have you solved this problem?

No, the accuracy is still only ~20%.

**Comment by XJKunnn** [comment]
Hi, maybe you can try to use a larger chunksize for aloha simulation environment by setting `n_action_steps` and `horizon` in config for diffusion policy:

```
horizon = 128
n_action_steps = 100
```

**Comment by jiangranlv** [comment]
Hi, have anyone solved this problem now?

**Comment by jiangranlv** [comment]
@CallMeFrozenBanana hi bro, i met the same issue and cannot reproduce your result with simply changing the crop size and crop center.

**Comment by Kimho666** [comment]
> [@CallMeFrozenBanana](https://github.com/CallMeFrozenBanana) hi bro, i met the same issue and cannot reproduce your result with simply changing the crop size and crop center.

For pusht env, if you use act policy. The chunsize must be small such as 8. The accuracy will be improved. But for aloha env, I dont know.

**Comment by Zelo-S** [comment]
It looks like the original paper mentioned using Transformer for Diffusion, specifically from miniGPT. Maybe that could be relevant for this kind of task?

**Comment by ShengkaiWu** [comment]
Hi, have anyone solved this problem now?

**Comment by Zelo-S** [comment]
As per @CallMeFrozenBanana's config suggestions I was able to get 96% PC_SUCCESS on Transfer-Cube v0 scripted, using lerobot 829d2d1 commit. But strangely I haven't been able to replicate the results on other machines since. Here's a config if it helps anyone, would appreciate if you reported back on how your results went:
```yml
_wandb:
    value:
        cli_version: 0.22.2
        e:
            ysp2r7oebi2a8ao1c67an3xl70ar3q1b:
                args:
                    - --config_path
                    - alohaDiffusion_trainConfig.json
                    - --dataset.repo_id
                    - lerobot/aloha_sim_transfer_cube_scripted
                    - --policy.push_to_hub
                    - "false"
                    - --policy.type
                    - diffusion
                    - --policy.device
                    - cuda
                    - --step
                    - "100000"
                    - --wandb.project
                    - lerobot
                    - --output_dir
                    - outputs/train/2025-10-23/aloha_act-18_16_43
batch_size:
    value: 20
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: lerobot/aloha_sim_transfer_cube_scripted
        revision: null
        root: null
        streaming: false
        use_imagenet_stats: true
        video_backend: pyav
env:
    value:
        disable_env_checker: true
        episode_length: 400
        features:
            action:
                shape:
                    - 14
                type: ACTION
            agent_pos:
                shape:
                    - 14
                type: STATE
            pixels/top:
                shape:
                    - 480
                    - 640
                    - 3
                type: VISUAL
        features_map:
            action: action
            agent_pos: observation.state
            pixels/top: observation.images.top
            top: observation.image.top
        fps: 50
        max_parallel_tasks: 1
        obs_type: pixels_agent_pos
        render_mode: rgb_array
        task: AlohaTransferCube-v0
        type: aloha
eval:
    value:
        batch_size: 25
        n_episodes: 25
        use_async_envs: false
eval_freq:
    value: 20000
job_name:
    value: aloha_diffusion
log_freq:
    value: 200
num_workers:
    value: 4
optimizer:
    value:
        betas:
            - 0.95
            - 0.999
        eps: 1e-08
        grad_clip_norm: 10
        lr: 0.0001
        type: adam
        weight_decay: 1e-06
output_dir:
    value: outputs/train/2025-10-23/aloha_act-18_16_43
policy:
    value:
        beta_end: 0.02
        beta_schedule: squaredcos_cap_v2
        beta_start: 0.0001
        clip_sample: true
        clip_sample_range: 1
        crop_is_random: false
        crop_shape:
            - 440
            - 560
        device: cuda
        diffusion_step_embed_dim: 128
        do_mask_loss_for_padding: false
        down_dims:
            - 512
            - 1024
            - 2048
        drop_n_last_frames: 7
        horizon: 16
        input_features:
            observation.images.top:
                shape:
                    - 3
                    - 480
                    - 640
                type: VISUAL
            observation.state:
                shape:
                    - 14
                type: STATE
        kernel_size: 5
        license: null
        n_action_steps: 8
        n_groups: 8
        n_obs_steps: 2
        noise_scheduler_type: DDPM
        normalization_mapping:
            ACTION: MIN_MAX
            STATE: MIN_MAX
            VISUAL: MEAN_STD
        num_inference_steps: null
        num_train_timesteps: 100
        optimizer_betas:
            - 0.95
            - 0.999
        optimizer_eps: 1e-08
        optimizer_lr: 0.0001
        optimizer_weight_decay: 1e-06
        output_features:
            action:
                shape:
                    - 14
                type: ACTION
        prediction_type: epsilon
        pretrained_backbone_weights: null
        pretrained_path: null
        private: null
        push_to_hub: false
        repo_id: null
        scheduler_name: cosine
        scheduler_warmup_steps: 500
        spatial_softmax_num_keypoints: 32
        tags: null
        type: diffusion
        use_amp: false
        use_film_scale_modulation: true
        use_group_norm: true
        use_separate_rgb_encoder_per_camera: true
        vision_backbone: resnet18
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 20000
scheduler:
    value:
        name: cosine
        num_warmup_steps: 500
        type: diffuser
seed:
    value: 100000
steps:
    value: 100000
use_policy_training_preset:
    value: true
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null

```
